# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Brand.create(name: "22 Days nutrition", category: "chocolate", url: "https://i.ytimg.com/i/wtlEnrTM14YHFs26uRsOvw/mq1.jpg", is_ethical: TRUE)
Brand.create(name: "365 Dark Chocolate Bar", category: "chocolate", url: "https://addisoncox.files.wordpress.com/2016/01/whole-foods-market-to-open-365-value-oriented-store-chain.jpg", is_ethical: TRUE)
Brand.create(name: "A.D.D.", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Agostoni", category: "chocolate", url: "http://www.rampcreative.com/web/wp-content/uploads/2012/01/ramp_agostoni-630x321.jpg", is_ethical: TRUE)
Brand.create(name: "Ah!Laska", category: "chocolate", url: "http://www.ahlaska.com/images/ahlaska/ah_sub_logo.jpg", is_ethical: TRUE)
Brand.create(name: "Alce Nero’s dark chocolate", category: "chocolate", url: "http://www.legambiente.it/sites/default/files/images/aziende/alce_nero.jpg", is_ethical: TRUE)
Brand.create(name: "Allegro Coffee Company", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Allison’s Gourmet", category: "chocolate", url: "http://events.wtfveganfood.com/wp-content/uploads/2013/06/Screen-Shot-2013-06-05-at-2.42.51-PM.png", is_ethical: TRUE)
Brand.create(name: "ALOHA", category: "chocolate", url: "https://thefriendlyfig.files.wordpress.com/2015/02/aloha-superfood-chocolate.png?w=400", is_ethical: TRUE)
Brand.create(name: "Alter Eco", category: "chocolate", url: "http://static1.squarespace.com/static/53ebf479e4b074443ab35526/t/56d4b00e60b5e9eb4dba5cb8/1456779324461/AlterEco_Logo_CMYK_R_high-res.jpg?format=300w", is_ethical: TRUE)
Brand.create(name: "Alternativa 3", category: "chocolate", url: "http://naturjoying.com/tienda/img/cms/ALTERNATIVA3_2.jpg", is_ethical: TRUE)
Brand.create(name: "Amano", category: "chocolate", url: "https://foodfetepress.files.wordpress.com/2011/11/amanoblackgold_logo.jpg", is_ethical: TRUE)
Brand.create(name: "Amy’s", category: "chocolate", url: "https://pbs.twimg.com/profile_images/1119150296/amys_logo_twitter.jpg", is_ethical: TRUE)
Brand.create(name: "Amy’s DriveThru", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Andean Dream", category: "chocolate", url: "http://www.andeandream.com/images/NewADreamLogo-245x196.png", is_ethical: TRUE)
Brand.create(name: "Ananda", category: "chocolate", url: "http://d13z1xw8270sfc.cloudfront.net/origin/197144/ananda_logo.jpg", is_ethical: TRUE)
Brand.create(name: "Antidote", category: "chocolate", url: "https://pbs.twimg.com/profile_images/520615251599847424/EuCz_Uuc_400x400.png", is_ethical: TRUE)
Brand.create(name: "Angell Chocolate Bars", category: "chocolate", url: "http://3boysandadog.com/wp-content/uploads/2012/03/Angell-Logo-HIGH.jpg", is_ethical: TRUE)
Brand.create(name: "Ara Chocolat", category: "chocolate", url: "http://d1k0pk41fv5epv.cloudfront.net/wp-content/uploads/2015/06/ARA-logo.jpg", is_ethical: TRUE)
Brand.create(name: "Artisan du Chocolat", category: "chocolate", url: "http://artisan-artisanduchocola.netdna-ssl.com/skin/frontend/novaworks/bearstore/images/logo.png", is_ethical: TRUE)
Brand.create(name: "Artisana", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Askinosie", category: "chocolate", url: "https://askinosie.com/skin/frontend/rwd/default/images/logo.jpg", is_ethical: TRUE)
Brand.create(name: "BEAR", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Be.Raw. Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Bixby Bar: ONLY Birdie, Heart’s Delight & Whippersnapper", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Bonnievilles", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Bonvita", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Booja-Booja", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Briskbars", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Budi Bar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Bulletproof", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "CaCoCo", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Charm School Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Choc & Nut", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "CHOC Chick Raw Chocolates Ltd.", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "ChocAlive!", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cocanú", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "ChocStars", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolate Amatller", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolate and Love", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolate Decadence", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolate Hollow", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolate Ibarra", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolate Inspirations, Inc", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolates El Rey", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chocolatl", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "chocolita", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "ChocoSol Traders", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Choquiero Organic chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chuao Chocolatier", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Chunks of Energy", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ciranda", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Claudio Corallo", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Coco Caravan", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cocoa Cravings", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cocoa Loco", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "CocoLicious", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cocolo", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Coconut Bliss", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Coconut Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Coconut Secret", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Coco-Zen", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Conscious Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "The Cookie Counter", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "The Co-operative", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Coracao Confections", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Core Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cornbread Café", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cotton Tree Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Crispy Cat", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Cupcake Royale", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Dandelion Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Dave’s Midnight Bakery", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Denman Island Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Divine", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Divine Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Earth Balance", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Earth Circle Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "East Maui Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "eat chic", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Eat Pastry", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Edensoy", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Elevate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Eli Bars", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Emmy’s Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Endangered Species Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Endorfin", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Equal Exchange", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Essential Living Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "eSutras organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ethicoco", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "evo hemp", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "The Fearless Chocolate Company", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "feedyourface", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Feel Good Desserts", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Frontier", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Full Tilt Ice Cream", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Garden of Life", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Gefle Chocolaterie", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Gemini", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Genuto", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Giddy Yoyo", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Global Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Gnosis", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Gone Pie Vegan Bakery", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "GO*DO Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Go Macro’s Peanut Butter Chocolate Chip Crunch", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Go Raw", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Gopal’s Healthfoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Goss Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Great Bean", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Healthforce Superfoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Herbs America", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Holy Kakow Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Honest Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Hot Cakes Molten Chocolate Cakery", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Hotel Chocolat", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "iChoc", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Il Modicano", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "inSpiral", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "IQ Superfood Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Jelina Chocolatier", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Jem Raw Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Jen’s Zen", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "JJ’s Sweets", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Jollyum", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Just Pure Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Justin’s Nut Butter", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Kaia Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Kakaw Belizean Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Kallari Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Keen-wah", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Kopali Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "kosuma Whole Food Energy™", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Kroger Cocoa Powder", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Kur Organic Superfoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "La Siembra Cocoa Camino", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lagusta’s Luscious", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "L’Amourette", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lake Champlain Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Late July", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Liebhart’s Gesundkost", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lifefood", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Live On Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Live Superfoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Living Food of St. Ives", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Living Raw", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "LivWell, LLC", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Love Bean", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Love Street Livin", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lovechock", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lovecrafted Vegan Baking", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lover Raw Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Loving Earth", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lulu’s Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lune Chocolat", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Lydia’s Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Madécasse’s Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Madre Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Mama Ganache", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Manifest Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Manifesto Cacao", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Manoa Chocolate Hawaii", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Marks & Spencer", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Marthomi", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Mary’s Gone Crackers", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Mast Brothers Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Mayesa", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Metabolic Response Modifiers", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Michel Cluizel", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Mindo Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Mister Sister", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Molly Moon’s", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Molucca Craft Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Montezuma’s", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Moo Free Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Multiple Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "MULU Organic Raw Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Natur-a", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Natural Balance Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Nature’s Path", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Navitas Naturals", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Nelly’s Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Newman’s Own", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "New Tree", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "New York Superfoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "NibMor", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Nicobella Organics", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Nirvana Belgian Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "No Cow Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Noah & Co.", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Not Your Sugar Mamas", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Nova Monda Cacao & Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Numi Organic Tea", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Nutiva", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "NuttZo", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "The Oakland Chocolate Company", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Oaxacabar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Obsessive Confection Disorder", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ombar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Omnon", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "One Degree Organic Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Organica", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Organic Nectars", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Original Beans", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Organic Fair", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Organic Food Bar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Orgran", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ostara", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Pana Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Parliament Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "PASCHA", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Patric Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Perfect Fit", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Perfect Fuel Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Plamil", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Poco Dolce", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "PRANA", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "President’s Choice", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Pulsin’", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Pure Bar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Raaka Virgin Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rainbow Bakery", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ranger Chocolate Company", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rapunzel", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rausch Plantagen-Shokolade", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "the raw chocolate co", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rawmio", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Raw Ecstasy", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Raw Health", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Raw Imagination", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Raw Nibbles", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Raw Revolution", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "RAWR Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rawxies", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Real Bar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Real Food Source", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "René Rey Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "República del Cacao", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rescue Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Righteously Raw", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ritual Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Rogue Chocolatier", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Roo’Bar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sacred Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Salazon Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sambazon", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Santa Barbara Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Santosha Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "SaviSeed", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Scarborough Fair", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Science Kitchen", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Scream Sorbet", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Seed and Bean Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Shaman Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Simply Raw", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sjaak’s Organic Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Skydottir Epic Cookies", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "So Delicious® Dairy Free", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Solkiki", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Spagnvola", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Squarebar", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Stirs the Soul", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sunburst Superfoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sunflour Baking Company", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sunfood’s Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sweet Eats", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sweet & Sara", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sweet Revolution", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Sweetriot", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Taza Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Teeccino", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Temptation", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Tesco Single Origin Bars only", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Theo Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Thesis", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Tierra Farm", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Travel Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "TruJoy Sweets", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Twenty-Four Blackbirds Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ulimana", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Ultimate SuperFoods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Vegan Treats", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Veganica Pty Ltd", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Vego", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Videri Chocolate Factory", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Vitacost Brand", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Vivani", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "VO2 Vegan Cafe", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Wei of Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "well.fed. by Alicia Smiley", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "The Wellington Chocolate Factory", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Wellness Foods", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Whistler Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Wholesome Chow", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Wild Boar’s Dark Chocolate", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Wilderness Family Naturals", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Wonder Food Company", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Woodblock Chocolate Manufactory", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "YAWP!", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "YesCacao", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Zenergy Powerballs", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Zimt Artisan Chocolates", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Zing Nutrition Bars", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Zotter", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "Fechlin", category: "chocolate", url: "", is_ethical: TRUE)
Brand.create(name: "TCHO", category: "chocolate", url: "http://www.candyindustry.com/ext/resources/images/February-2013-EVERYDAY/Tcho_logo_thumb.jpeg", is_ethical: TRUE)